%% Options 
%% Paths 
Options.Paths = struct( ...
    'path2ROI',input_parameters{4,"Paths_dir"},...
    'CDF', input_parameters{5,"Paths_dir"}, ...
    'CDF_MS2','',...
    'save2mat',fullfile(input_parameters{3,"Paths_dir"}{:}));

%% ROI 
Options.ROI = struct( ...
    'minroi',input_parameters{1,"ROI_value"},...
    'mzerror',input_parameters{2,"ROI_value"},...
    'ppm',input_parameters{3,"ROI_value"} == 1,...
    'thresh',input_parameters{4,"ROI_value"},...
    'wmean',true,...
    'GapAllowed',input_parameters{5,"ROI_value"},...
    'NumTrace',input_parameters{9,"ROI_value"},...
    'verbose',false,...
    'prefilter',true,...
    'fillIn',0, ...
    'IMS',false,...
    'SumMSLevels',false,...
    'MS1_Suffix','CDF',...
    'MS2_Suffix','CDF',...
    'RemoveSuffix',6); % Remove the last letters in the sample name in case you have MS2 data obtained in data-independent mode

Options.ROI.mzOptimization = struct( ...
    'MZmultiplyFactors', 1:input_parameters{7,"ROI_value"}:input_parameters{6,"ROI_value"}, ...
    'nSamples',input_parameters{8,"ROI_value"}, ...
    'mzerror', Options.ROI.mzerror);
%%
addpath(Options.Paths.path2ROI)
addpath([Options.Paths.path2ROI,'\ParWaitBar\'])

%%
Options.ROI


